# Generated by Django 5.2.6 on 2025-09-19 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_candidateprofile_experience_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='salary_range_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='salary_range_min',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
