# Generated by Django 5.2.6 on 2025-09-21 00:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_candidateprofile_salary_range_max_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name="Nom de l'entreprise")),
                ('description', models.TextField(verbose_name="Description de l'entreprise")),
                ('secteur_activite', models.CharField(max_length=100, verbose_name="Secteur d'activité")),
                ('localisations', models.JSONField(default=list, verbose_name='Localisations')),
                ('adresse', models.TextField(verbose_name='Adresse')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('site_web', models.URLField(blank=True, verbose_name='Site web')),
                ('logo', models.ImageField(blank=True, upload_to='logos/', verbose_name='Logo')),
                ('position_google_maps', models.URLField(blank=True, verbose_name='Position Google Maps')),
                ('numero_service_client', models.CharField(blank=True, max_length=20, verbose_name='Numéro service client')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Entreprise vérifiée')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_validation', models.DateTimeField(auto_now_add=True, verbose_name='Date de validation')),
                ('statut_validation', models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('rejete', 'Rejeté')], default='en_attente', max_length=20, verbose_name='Statut de validation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('administrateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entreprise', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entreprise',
                'verbose_name_plural': 'Entreprises',
                'ordering': ['-date_creation'],
            },
        ),
    ]
