# Generated by Django 5.2.6 on 2025-09-24 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_annee_diplome_user_competences_user_cv_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='cv_file_base64',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='profile_photo_base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
