services:
  - type: web
    name: jobstage-backend
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --noinput"
    startCommand: "gunicorn jobstage_backend.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "jobstage-backend.onrender.com"
      - key: CORS_ALLOW_ALL_ORIGINS
        value: "True"
      - key: DATABASE_URL
        fromDatabase:
          name: jobstage-db
          property: connectionString
      - key: PYTHON_VERSION
        value: "3.12.0"

  - type: pserv
    name: jobstage-db
    env: postgresql
    plan: free
